---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "charts.labels" . | nindent 4 }}
data:
  ST_SERVER_PORT: 8080
  ST_METRICS_PORT: 8081
  ST_USER: admin
  ST_PASSWORD: password
